### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by akafester** [RMoRobert/CoCoConz#1]
I found this app by accident, but I'm liking it thus far. 

I think I found a problem with the button driver. No matter how much I press them, nothing happens. 
Nothing in the logs either.

Found this if you can use it: https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/sensors/button_events/
They follow a logic. First number is the button and the last number is the event. 1 held, 2 pushed, 3 released.

The Philips TAP is diffrent though.
That uses 
- Button 1: 34
- button 2: 16
- button 3: 17 
- button 4: 18

**Comment by RMoRobert** [comment]
There is another deCONZ/Phoscon integration you can find on the forum that I might recommend using for now; I no longer have a functioning deCONZ setup, and this integration was something I played around with when I did. (Surprised you found it--never posted about it in the forums!) That being said, it looks like I do have newer code saved locally than I have uploaded to GitHub, so I can try uploading that if you want, though I have no idea if it's complete at this point...

**Comment by akafester** [comment]
I stumbled on it because I had issues with the one on the forum, or so I thought. So I wanted to see if there were any alternatives, and stumbled across your repo. I like the app form and it seems it would be easier to manage. Wasn't sure though so I thought I would chime in :).
For posterity, and if someone else sees the potential in the app, I would recommend it. But it's entirely up to you of course :) 

Thank you for your time.
